/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.google;

import java.io.IOException;
import java.util.List;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author J2EE-33
 */
public class From extends javax.swing.JFrame {

    /**
     * Creates new form From
     */
    public From() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fEmail = new javax.swing.JTextField();
        fAge = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fMale = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        fFemale = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        fReading = new javax.swing.JCheckBox();
        fWriting = new javax.swing.JCheckBox();
        fCoding = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        fRound = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fNote = new javax.swing.JTextArea();
        fDisplay = new javax.swing.JLabel();
        fAdd = new javax.swing.JButton();
        fClean = new javax.swing.JButton();
        fFile = new javax.swing.JButton();
        fTable = new javax.swing.JButton();
        fExit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Students from", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Students information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel2.setText("Name");

        fName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Email");

        fAge.setText("0");
        fAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fAgeActionPerformed(evt);
            }
        });
        fAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fAgeKeyReleased(evt);
            }
        });

        jLabel4.setText("Age");

        fMale.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup1.add(fMale);
        fMale.setText("Male");

        jLabel5.setText("Gender");

        fFemale.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup1.add(fFemale);
        fFemale.setText("Female");

        jLabel6.setText("Hobby");

        fReading.setBackground(new java.awt.Color(204, 255, 255));
        fReading.setText("Reading");

        fWriting.setBackground(new java.awt.Color(204, 255, 255));
        fWriting.setText("Writing");

        fCoding.setBackground(new java.awt.Color(204, 255, 255));
        fCoding.setText("Coding");

        jLabel7.setText("Round");

        fRound.setBackground(new java.awt.Color(204, 255, 255));
        fRound.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Round", "33", "34", "35" }));
        fRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fRoundActionPerformed(evt);
            }
        });

        jLabel8.setText("Note");

        fNote.setColumns(20);
        fNote.setRows(5);
        jScrollPane1.setViewportView(fNote);

        fAdd.setBackground(new java.awt.Color(204, 204, 255));
        fAdd.setText("Add to Table");
        fAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fAddActionPerformed(evt);
            }
        });

        fClean.setBackground(new java.awt.Color(204, 255, 255));
        fClean.setText("Clear From");
        fClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fCleanActionPerformed(evt);
            }
        });

        fFile.setBackground(new java.awt.Color(204, 255, 255));
        fFile.setText("Read from flile");
        fFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fFileActionPerformed(evt);
            }
        });

        fTable.setBackground(new java.awt.Color(204, 255, 255));
        fTable.setText("Clear Table");
        fTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTableActionPerformed(evt);
            }
        });

        fExit.setBackground(new java.awt.Color(204, 255, 255));
        fExit.setText("Exit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fDisplay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(fMale)
                        .addGap(18, 18, 18)
                        .addComponent(fFemale))
                    .addComponent(fEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(fName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(fReading)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fWriting)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fCoding))
                    .addComponent(fAge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(fRound, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(fFile)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(fTable)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fExit))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(fAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(fClean))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fAge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fMale)
                    .addComponent(fFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fReading)
                    .addComponent(fCoding)
                    .addComponent(fWriting))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(fDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(fClean, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fFile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fTable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Show Table", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jScrollPane2.setBackground(new java.awt.Color(255, 204, 204));

        tTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Age", "Gender", "Hobby", "Round", "Note"
            }
        ));
        tTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_fNameActionPerformed

    private void fAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fAddActionPerformed
        // TODO add your handling code here:
        String name = "", email = "", age = "0", gender = "", hobby = "", round = "", note = "";
        if (fName.getText().length() < 1) {
            JOptionPane.showMessageDialog(null, "Enter your name");
        } else if (!CheckEmailValidity(fEmail.getText()) || fEmail.getText().length() < 1) {
            JOptionPane.showMessageDialog(null, "Enter your Email");
        } else if (Integer.parseInt(fAge.getText()) < 18 || Integer.parseInt(fAge.getText()) > 72) {
            JOptionPane.showMessageDialog(null, "Enter your Age");
        } else if (buttonGroup1.getSelection().isSelected() == false) {
            JOptionPane.showMessageDialog(null, "Enter your Gender");
        } else if (!fReading.isSelected() && !fWriting.isSelected() && !fCoding.isSelected()) {
            JOptionPane.showMessageDialog(null, "Select your Hobby");
        } else if (fRound.getItemAt(fRound.getSelectedIndex()) == "Select a Round") {

            JOptionPane.showMessageDialog(null, "Select a round");
        } else if (fNote.getText().length() < 5) {
            JOptionPane.showMessageDialog(null, "Write a short note");
        } else {
            name = fName.getText();
            email = fEmail.getText();
            age = fAge.getText();
            gender = "";
            if (fMale.isSelected()) {
                gender = fMale.getText();
            }
            if (fFemale.isSelected()) {
                gender = fFemale.getText();
            }
            hobby = "";
            if (fReading.isSelected()) {
                hobby += fReading.getText();
            }
            if (fWriting.isSelected()) {
                hobby += fWriting.getText();
            }
            if (fCoding.isSelected()) {
                hobby += fCoding.getText();
            }
            round = fRound.getItemAt(fRound.getSelectedIndex());
            note = fNote.getText();

            Students student = new Students(name, email, Integer.parseInt(age), gender, hobby, round, note);
            List<Students> s = new ArrayList<>();
            s.add(student);
            DefaultTableModel model = (DefaultTableModel) tTable.getModel();
            Object[] col = new Object[7];
            for (int i = 0; i < s.size(); i++) {
                col[0] = s.get(i).getName();
                col[1] = s.get(i).getEmail();
                col[2] = s.get(i).getAge();
                col[3] = s.get(i).getGender();
                col[4] = s.get(i).getHobby();
                col[5] = s.get(i).getRound();
                col[6] = s.get(i).getNote();
                model.addRow(col);

                try {
                    Utils.writeToFile("students", s);
                } catch (IOException ex) {
                    Logger.getLogger(From.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            fDisplay.setText("Successfully Addedinto table ang write to file");
        }


    }//GEN-LAST:event_fAddActionPerformed

    private void fCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fCleanActionPerformed
        // TODO add your handling code here:
        fName.setText("");
        fEmail.setText("");
        fAge.setText("");
        buttonGroup1.clearSelection();
        fReading.setSelected(false);
        fWriting.setSelected(false);
        fCoding.setSelected(false);
        fRound.setSelectedIndex(0);
        fNote.setText("");
        fDisplay.setText("");

    }//GEN-LAST:event_fCleanActionPerformed

    private void fTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTableActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tTable.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_fTableActionPerformed

    private void fFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fFileActionPerformed
        // TODO add your handling code here:
        String columns[] = {"Name", "Email", "Age", "Gender", "Hobby", "Round", "Note"};
        DefaultTableModel tabelModel;
        tabelModel = new DefaultTableModel(0, 7);
        tabelModel.setColumnIdentifiers(columns);
        tTable.setModel(tabelModel);
        Utils.displayStudentsInformationFromFile("students", tabelModel);
    }//GEN-LAST:event_fFileActionPerformed

    private void tTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tTableMouseClicked
        // TODO add your handling code here:
          int i = tTable.getSelectedRow();
        TableModel model = tTable.getModel();
        fName.setText(model.getValueAt(i, 0).toString());
        fEmail.setText(model.getValueAt(i, 1).toString());
        fAge.setText(model.getValueAt(i, 2).toString());

        String gender = model.getValueAt(i, 3).toString();
        if (gender.equals("Male")) {
            fMale.setSelected(true);
        } else {
            fMale.setSelected(false);
        }

        if (gender.equals("Female")) {
            fFemale.setSelected(true);
        } else {
            fFemale.setSelected(false);
        }

        String hobby = model.getValueAt(i, 4).toString();
        if (hobby.contains("Reading")) {
            fReading.setSelected(true);
        } else {
            fReading.setSelected(false);
        }

        if (gender.equals("Writing")) {
            fWriting.setSelected(true);
        } else {
            fWriting.setSelected(false);
        }
        if (gender.equals("Coding")) {
            fCoding.setSelected(true);
        } else {
            fCoding.setSelected(false);
        }
        String round = model.getValueAt(i, 5).toString();
        fRound.setSelectedItem(round);
        fNote.setText(model.getValueAt(i, 6).toString());


    }//GEN-LAST:event_tTableMouseClicked

    private void fRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fRoundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fRoundActionPerformed

    private void fAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fAgeActionPerformed

    private void fAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fAgeKeyReleased
        // TODO add your handling code here:
        char ch= evt.getKeyChar();
        if(Character.isAlphabetic(ch)){
        JOptionPane.showMessageDialog(null, "Only numbers are allowed");
        fAge.setText("0");
        }
    }//GEN-LAST:event_fAgeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new From().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton fAdd;
    private javax.swing.JTextField fAge;
    private javax.swing.JButton fClean;
    private javax.swing.JCheckBox fCoding;
    private javax.swing.JLabel fDisplay;
    private javax.swing.JTextField fEmail;
    private javax.swing.JButton fExit;
    private javax.swing.JRadioButton fFemale;
    private javax.swing.JButton fFile;
    private javax.swing.JRadioButton fMale;
    private javax.swing.JTextField fName;
    private javax.swing.JTextArea fNote;
    private javax.swing.JCheckBox fReading;
    private javax.swing.JComboBox<String> fRound;
    private javax.swing.JButton fTable;
    private javax.swing.JCheckBox fWriting;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tTable;
    // End of variables declaration//GEN-END:variables

    private boolean CheckEmailValidity(String email) {
        if (null != email) {
            String regex = "^([_a-zA-Z0-9-]+(\\.[_a-zA-Z0-9-]+)*@[a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)*(\\.[a-zA-Z]{1,6}))?$";
            Pattern pattern = Pattern.compile(regex);
            Matcher matcher = pattern.matcher(email);
            if (!matcher.matches()) {
                return false;
            }
            return true;
        }
        return false;
    }
}
